server:
  port: 7777

logging:
  level:
    org:
      springframework:
        boot: INFO
    pl:
      futurecollars:
        invoicing: INFO
  invoicing.db: DEBUG

spring:
  profiles:
    aactive: jpa-flyway
  flyway:
    enabled: false